### ISSUE TITLE
sqlite database external

### ISSUE THREAD

**Issue by StephanKrauss** [Dev-Crea/taskboard#1]
Hello,

i will use for my work the taskboard.
I have a problem.
I will save the sqlite file external.

I found this information:
docker run --name arantia-tasks -p 8100:80 -v $PWD/taskboard.db:/var/www/html/api/taskboard.db rmorgade/taskboard

Sorry, i'm a beginner in docker.
Can you give me an information ?

Your sincerly

Stephan

**Comment by Dev-Crea** [comment]
Hi, your command is not correct. If you use this name `rmorgade/taskboard` you don't use my image (`devcrea/taskboard`).

Try this : `docker run --name <your-name-container> -p 8100:80 -v $(pwd)/taskboard.db:/var/www/html/api/taskboard.db devcrea/taskboard`
